inherit_from: 
  - .rubocop-airbnb.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - node_modules/**
    - db/**
    - config/**/*
    - bin/**/*
    - script/**
    - vendor/**/* # Circle adds the rubies here
    - spec/spec_helper.rb # Circle adds the rubies here