language: node_js 
node_js: '13.9.0'
services:
  - mysql
before_install:
  - rvm install 2.5.7
  - gem install bundler
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version  
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci';
env:
  - NODE_ENV=test
before_script: 
  - 'bundle install'
  - 'bundle exec rails assets:precompile'
jobs:
  include:
    - stage: rspec
      script: 'bundle exec rspec'
    - stage: linter 
    - name: rubocop
      script: 'bundle exec rubocop'
    - name: haml linter
      script: 'bundle exec haml-lint app/views'
