language: ruby 
ruby: '2.5.7'
services:
  - mysql
before_install:
  - nvm install 13.9.0
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version  
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci';
jobs:
  include:
    - stage: rspec
      env: NODE_ENV=test
      before_script: 
        - 'bundle install'
        - 'bundle exec rails assets:precompile'
      script: 'bundle exec rspec'
    - stage: linter 
      name: rubocop
      env: NODE_ENV=test
      script: 'bundle exec rubocop'
    - name: haml linter
      env: NODE_ENV=test
      script: 'bundle exec haml-lint app/views'
