language: ruby
rvm:
  - '2.5.7'
services:
  - mysql
before_install:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version  
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci';
jobs:
  include:
    - stage: rspec
      script: 'bundle exec rspec'
    - stage: rubocop
      script: 'bundle exec rspec'